backend: apt
modules:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - packages
  - bootloader
  - services-systemd
  - umount

sequence:
  - show: [welcome, locale, keyboard]
  - show: [partition, users]
  - exec: [packages, bootloader, services-systemd]
  - show: [umount]

branding: kodi
prompt-install: true
unsafe: false
